name: synch_de
channels:
  - conda-forge
dependencies:
  - python=3.12
  - black
  - flake8
  - isort
  - condax
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - nbautoexport # Exports Jupyter Notebooks to Python scripts when saved from jupyter server https://drivendata.co/blog/nbautoexport-jupyter-code-review/
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - pip:
      - python-dotenv
      - mkdocs
      - -e .
