name: synch_de
channels:
  - conda-forge
dependencies:
  - python=3.12
  - black
  - flake8
  - ipython
  - isort
  - condax
  - dask
  - pip
  - conda
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - nbautoexport # Exports Jupyter Notebooks to Python scripts when saved from jupyter server https://drivendata.co/blog/nbautoexport-jupyter-code-review/
  - notebook
  - numpy
  - pandas
  - pytest
  - scikit-learn
  - seaborn
  - ydata-profiling
  - mkdocs
  - python-dotenv
  - pip:
      - -e .
